sudo: required
services: 
  - docker

before_install:
  - docker build -t yasir326/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true yasir326/react-test npm run test -- --coverage

after_success:
  - docker build -t yasir326/multi-client ./client
  - docker build -t yasir326/multi-nginx ./nginx
  - docker build -t yasir326/multi-server ./server
  - docker build -t yasir326/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  #Take images and push to docker hub
  - docker push yasir326/multi-client
  - docker push yasir326/multi-nginx
  - docker push yasir326/multi-server
  - docker push yasir326/multi-worker
